receivers:
  hostmetrics:
    collection_interval: 5s
    scrapers:
      cpu:
        metrics:
          system.cpu.frequency:
            enabled: true
          system.cpu.logical.count:
            enabled: true
          system.cpu.physical.count:
            enabled: true
          system.cpu.utilization:
            enabled: true

exporters:
  otlp:
    endpoint: localhost:4317
    tls:
      insecure: true
  file:
    path: hostmetrics.log
    rotation:

service:
  telemetry:
    metrics:
      level: none
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [otlp, file]
